<?php
namespace FormLister;

/**
 * Контроллер для отправки данных в TelegramBot
 * Class SendBot
 * @package FormLister
 */
class SendBot extends Core
{
	public function __construct (DocumentParser $modx, $cfg = [])
	{
		parent::__construct($modx, $cfg);
		$this->lexicon->fromFile('sendbot');
        $this->log('Lexicon loaded', ['lexicon' => $this->lexicon->getLexicon()]);
	}

	/**
	 * Загружает в formData данные не из формы
	 * @param string $sources список источников
	 * @param string $arrayParam название параметра с данными
	 * @return $this
	 */
	public function setExternalFields ($sources = 'array', $arrayParam = 'defaults')
	{
		parent::setExternalFields($sources, $arrayParam);
		return $this;
	}


	/**
	 * @return string
	 */
	public function render ()
	{
		return parent::render();
	}

	public function getValidationRules($param = 'rules')
	{
		$rules = parent::getValidationRules($param); // TODO: Change the autogenerated stub
		/**
		$password = $this->getField('password');
		if (empty($password) || !is_scalar($password)) {
			$this->forbiddenFields[] = 'password';
			if (isset($rules['password'])) {
				unset($rules['password']);
			}
			if (isset($rules['repeatPassword'])) {
				unset($rules['repeatPassword']);
			}
		} else {
			if (isset($rules['repeatPassword']['equals'])) {
				$rules['repeatPassword']['equals']['params'] = $this->getField('password');
			}
		}
		**/
		return $rules;
	}

	/**
	 *
	 */
	public function process ()
	{
		/**
		 * Проверка
		 **/
		/**
		$this->log('Update profile', [
			'data'   => $fields,
			'result' => $result,
			'log'    => $this->user->getLog()
		]);
		**/
		/**
		 * Отправка
		 **/
		if ($result) {
			$this->setFormStatus(true);
			//$this->user->close();
			//$this->setFields($this->user->edit($result)->toArray());
			//if ($dob = $this->fromTimestamp($this->getField('dob'))) {
			//	$this->setField('dob', $dob);
			//}
			//$this->setField('user.password', $newpassword);
			$this->runPrepare('preparePostProcess');
			$this->runPrepare('prepareAfterProcess');
			//$checkActivation = $this->getCFGDef('checkActivation', 0);
			//if ($checkActivation && !$this->getField('verified')) {
			//	$this->user->logOut('WebLoginPE', true);
			//	$this->redirect('exitTo');
			//}
			$this->redirect();
			if ($successTpl = $this->getCFGDef('successTpl')) {
				$this->renderTpl = $successTpl;
			} else {
				$this->addMessage($this->translate('sendbot.send_success'));
			}
		} else {
			$this->addMessage($this->translate('sendbot.send_failed'));
		}
	}
}